### PR TITLE
#26: Add replacement parameters for TODO items

### PR DESCRIPTION
**Pull request by kMutagene**
This PR adds optional parameters to pass to `dotnet new Waypoint` that fill the TODO placeholders in build.fsx and licence.md.

here's an example output:

`PS C:\Users\kevin\source\repos\kMutagene\wptest> dotnet new Waypoint --summary "test summary pls ignore" --authors "meem, soos" --packageTags "some tags m8" --copyright "me" --gitOwner "dueMcDudeson" --force`

generated build.fsx:

image

This also generates a nice `--help` output:

`PS C:\Users\kevin\source\repos\kMutagene\wptest> dotnet new Waypoint --help`

image

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Awesome. 😍

One more TODO is in the docs, can also provide the setting for it? - https://github.com/ionide/Waypoint/blob/master/Content/docs/loaders/globalloader.fsx#L26

**Comment by kMutagene** [comment]
Yeah sorry, missed that one somehow. Should be coming in any minute.

**Comment by Krzysztof-Cieslak** [comment]
Awesome, thanks a lot!

**Comment by kMutagene** [comment]
No worries, happy to help such a cool project!

**Pull request merged**
